export interface Renaes {
    Institución:                                               string;
    EES:                                                       string;
    "Código Único":                                            string;
    "Nombre del establecimiento":                              string;
    Microrred:                                                 string;
    Red:                                                       string;
    "Unidad Ejecutora":                                        string;
    "Código UE":                                               string;
    Categoria:                                                 string;
    "Quintil Belga":                                           string;
    Belga:                                                     string;
    "Quintil Regional":                                        number;
    "Quintil Nacional":                                        number;
    FON:                                                       string;
    FED:                                                       string;
    Clasificación:                                             string;
    Tipo:                                                      string;
    Departamento:                                              string;
    Provincia:                                                 string;
    Distrito:                                                  string;
    UBIGEO:                                                    string;
    Dirección:                                                 string;
    "Código DISA":                                             string;
    "Código Red":                                              string;
    "Código Microrred":                                        string;
    DISA:                                                      string;
    Teléfono:                                                  string;
    "Tipo Doc#Categorización":                                 string;
    "Nro#Doc#Categorización":                                  string;
    Horario:                                                   string;
    "Inicio de Actividad":                                     string;
    "Director Médico y/o Responsable de la Atención de Salud": string;
    Estado:                                                    string;
    Situación:                                                 string;
    Condición:                                                 string;
    Inspección:                                                string;
    NORTE:                                                     string;
    ESTE:                                                      string;
    COTA:                                                      string;
    CAMAS:                                                     string;
    RUC:                                                       string;
}
